use serde::Deserialize;

#[derive(Deserialize)]
pub enum Action {
    ShiftCursorLeft,
    ShiftCursorRight,
    ShiftCursorUp,
    ShiftCursorDown,
    ShiftCursorDocStart,
    ShiftCursorDocEnd,
    ShiftCursorLineStart,
    ShiftCursorLineEnd,
    ShiftCursorTokenStart,
    ShiftCursorTokenEnd,
    Save,
    Open,
    Close,
    Delete,
    DeleteLine,
    Insert,
    Cut,
    Copy,
    Paste,
    Undo,
    Redo,
    Select,
    SelectAll,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Indent,
    Dedent,
    Search,
    Exit,
}

#[derive(Deserialize)]
pub enum ActionResult {
    Unhandled,
    Null,
    CursorShifted { line: usize, col: usize, idx: usize },
    Saved,
    Opened,
    Closed,
    Deleted,
    DeletedLine,
    Inserted,
    Cut,
    Copied,
    Pasted,
    Undone,
    Redone,
    Selected,
    SelectedAll,
    Bolded,
    Italicized,
    Underlined,
    Struckthrough,
    Indented,
    Dedented,
    Searched,
    Exited,
}
